name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name my-redis

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Make mvnw executable
      run: chmod +x mvnw

    - name: Build and test with Maven
      run: ./mvnw -q test

    - name: Upload code coverage report to Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)

  cache:
    directories:
      - $HOME/.m2/repository
