name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name my-redis

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin' # Changed from 'adopt' to 'temurin'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Build and test with Maven
      run: mvn -q test -Dmaven.test.failure.ignore=true

    - name: Upload code coverage report to Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: $HOME/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
