name: Java CI with Redis

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8 and Maven
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Verify Maven Wrapper
      run: chmod +x mvnw

    - name: Run Maven install
      run: ./mvnw -q install -Dgpg.skip

    - name: Run Maven test
      run: ./mvnw -q test


