name: gha-result
on:
  workflow_dispatch:
  push:
    branches:
    - branch-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0

    - name: Set up cache
      uses: actions/cache@v3.3.1
      with:
        path: "${{ github.workspace }}/.m2/repository"
        key: "${{ runner.os }}-path"

    - name: Set up Java
      uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: '8'

    - name: Configure Maven
      run: |
        mkdir -p $HOME/.m2
        echo "<settings><localRepository>${{ github.workspace }}/.m2/repository</localRepository></settings>" > $HOME/.m2/settings.xml

    - name: Make mvnw executable
      run: chmod +x mvnw

    - name: Run Maven tests with ignoring failures
      run: mvn -q -Dmaven.test.failure.ignore=true test

    - name: Upload coverage report
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
