name: gha-result

on:
  workflow_dispatch:
  push:
    branches:
      - branch-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Apache Maven
        run: |
          MAVEN_VERSION=3.8.4
          wget -q https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          tar xf apache-maven-${MAVEN_VERSION}-bin.tar.gz
          echo "M2_HOME=$PWD/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "$PWD/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Run Maven tests
        run: mvn -q test

      - name: Upload coverage report
        if: success()
        run: bash <(curl -s https://codecov.io/bash)
