name: gha-result
on:
  workflow_dispatch:
  push:
    branches:
    - branch-1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Set up cache
      uses: actions/cache@v3.3.1
      with:
        path: "${{ github.workspace }}/.m2/repository"
        key: "${{ runner.os }}-path"
    - name: Download Apache Maven
      run: |
        wget -q https://apache.osuosl.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
        tar xf apache-maven-3.8.4-bin.tar.gz
        export PATH=$(pwd)/apache-maven-3.8.4/bin:$PATH
    - name: Make mvnw executable
      run: chmod +x mvnw
    - name: Start Redis Server
      run: sudo redis-server /etc/redis/redis.conf --port 6379
    - name: Run Maven tests
      run: "./mvnw -q test"
    - name: Upload coverage report
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
