name: gha-result
on:
  workflow_dispatch:
  push:
    branches:
    - branch-1

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAVEN_VERSION: '3.8.4'
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0

    - name: Set up cache
      uses: actions/cache@v3.3.1
      with:
        path: "${{ github.workspace }}/.m2/repository"
        key: "${{ runner.os }}-path"

    - name: Set up Java
      uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: '8'

    - name: Download Apache Maven
      run: |
        wget -q "https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz"
        tar xf "apache-maven-${MAVEN_VERSION}-bin.tar.gz"
        export PATH=$(pwd)/apache-maven-${MAVEN_VERSION}/bin:$PATH

    - name: Make mvnw executable
      run: chmod +x mvnw

    - name: Run Maven tests
      run: "./mvnw -q test"

    - name: Upload coverage report
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
