name: Java CI with Redis

on:
  push:
    branches:
      - 'branch-2'
  pull_request:
    branches:
      - 'branch-2'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven install and test
      run: |
        chmod +x mvnw
        ./mvnw -q install test -Dgpg.skip
