name: placeholder_Name

on:
  pull_request: {}
  push:
    branches:
      - branch-2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['1.8'] 
      fail-fast: false
    steps:
    - uses: actions/checkout@v2 

    - name: Set up JDK
      uses: actions/setup-java@v2 
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin' # Specify distribution
        cache: maven

    - name: Build and test with Maven
      run: |
        chmod +x mvnw
        ./mvnw -q test
